databases:
  - name: feeb-db
    databaseName: feeb
    user: feeb
    plan: free
    region: frankfurt

services:
  - type: web
    runtime: python
    name: feeb-api
    region: frankfurt
    plan: free
    branch: deployment
    rootDir: apps/api
    buildFilter:
      paths:
        - apps/api
    autoDeployTrigger: commit
    healthCheckPath: /health
    buildCommand: uv sync
    startCommand: uv run uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: feeb-db
          property: connectionString

  - type: web
    runtime: static
    name: feeb-web
    branch: deployment
    rootDir: apps/web
    buildFilter:
      paths:
        - apps/web
    autoDeployTrigger: commit
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://feeb.onrender.com
      - key: VITE_SUPABASE_URL
        value: https://ikojeprcvldqpfyugbkp.supabase.co
      - key: VITE_SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlrb2plcHJjdmxkcXBmeXVnYmtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA5OTQxODYsImV4cCI6MjA3NjU3MDE4Nn0.aaZigPDqE-vuhK3xKxGdCuXloWQUBl2a-IN-5KPluu0
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
