"""Create ingredient allergen tables

Revision ID: 2e56f4bddd34
Revises: 
Create Date: 2025-10-07 16:59:01.213610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e56f4bddd34'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergen',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('severity_level', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allergen_code'), 'allergen', ['code'], unique=True)
    op.create_index(op.f('ix_allergen_name'), 'allergen', ['name'], unique=False)
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('parent_code', sa.String(length=255), nullable=True),
    sa.Column('allergen_code', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('last_updated', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_code'), 'ingredient', ['code'], unique=True)
    op.create_index(op.f('ix_ingredient_name'), 'ingredient', ['name'], unique=False)
    op.create_index(op.f('ix_ingredient_source'), 'ingredient', ['source'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('lang', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_barcode'), 'product', ['barcode'], unique=True)
    op.create_table('ingredient_allergen',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('allergen_id', sa.Integer(), nullable=False),
    sa.Column('certainty', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergen.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredient_id', 'allergen_id', 'source', name='uq_ingredient_allergen_source')
    )
    op.create_table('product_allergen',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('allergen_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergen.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'allergen_id', 'relation_type', name='uq_product_allergen_relation')
    )
    op.create_table('product_ingredient',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('percent_estimate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'ingredient_id', name='uq_product_ingredient')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_ingredient')
    op.drop_table('product_allergen')
    op.drop_table('ingredient_allergen')
    op.drop_index(op.f('ix_product_barcode'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_ingredient_source'), table_name='ingredient')
    op.drop_index(op.f('ix_ingredient_name'), table_name='ingredient')
    op.drop_index(op.f('ix_ingredient_code'), table_name='ingredient')
    op.drop_table('ingredient')
    op.drop_index(op.f('ix_allergen_name'), table_name='allergen')
    op.drop_index(op.f('ix_allergen_code'), table_name='allergen')
    op.drop_table('allergen')
    # ### end Alembic commands ###

