"""add_base_prep_tables

Revision ID: 983e46a3217b
Revises: b92d4e2c2aad
Create Date: 2025-10-29 12:43:49.137685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '983e46a3217b'
down_revision: Union[str, None] = 'b92d4e2c2aad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_prep',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('yield_quantity', sa.DECIMAL(precision=10, scale=3), nullable=True),
    sa.Column('yield_unit', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('base_prep_ingredient',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('base_prep_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=10, scale=3), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('allergens', sa.Text(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['base_prep_id'], ['base_prep.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_prep_id', 'ingredient_id', name='uq_base_prep_ingredient')
    )
    op.create_table('recipe_base_prep',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('base_prep_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=10, scale=3), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['base_prep_id'], ['base_prep.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id', 'base_prep_id', name='uq_recipe_base_prep')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_base_prep')
    op.drop_table('base_prep_ingredient')
    op.drop_table('base_prep')
    # ### end Alembic commands ###

