"""sync models with database schema

Revision ID: ea066e9cba2d
Revises: 209f1206ecaf
Create Date: 2025-10-23 15:47:00.383048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea066e9cba2d'
down_revision: Union[str, None] = '209f1206ecaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_allergen_badge_code', 'allergen_badge', type_='unique')
    op.drop_constraint('menu_upload_restaurant_id_fkey', 'menu_upload', type_='foreignkey')
    op.create_foreign_key(None, 'menu_upload', 'restaurant', ['restaurant_id'], ['id'])
    op.alter_column('recipe_ingredient_substitution', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipe_ingredient_substitution', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'menu_upload', type_='foreignkey')
    op.create_foreign_key('menu_upload_restaurant_id_fkey', 'menu_upload', 'restaurant', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('uq_allergen_badge_code', 'allergen_badge', ['code'])
    # ### end Alembic commands ###

