[project]
name = "feeb-api"
version = "0.1.0"
description = "Allergen-Aware Ingredient API"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.0",
    "uvicorn[standard]>=0.32.0",
    "sqlalchemy>=2.0.0",
    "alembic>=1.13.0",
    "pydantic>=2.9.0",
    "pydantic-settings>=2.6.0",
    "httpx>=0.27.0",
    "asyncpg>=0.30.0",
    "python-multipart>=0.0.12",
    "pytest>=8.3.0",
    "pytest-asyncio>=0.24.0",
    "greenlet>=3.2.4",
    "psycopg2>=2.9.11",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["app", "data_pipeline", "alembic"]

